const sponsorImages = [
    { src: "/images/sterling.jpeg", alt: "Sterling" },
    { src: "/images/crusader.png", alt: "Crusader" },
    { src: "/images/nafc.jpg", alt: "NAFC" },
    { src: "/images/nbf.jpg", alt: "NBF" },
    { src: "/images/military.jpg", alt: "Military" },
    { src: "/images/stanbic.jpeg", alt: "Stanbic" },
    { src: "/images/bank.jpg", alt: "Bank" },
    { src: "/images/sterling.jpeg", alt: "Sterling" },
    { src: "/images/crusader.png", alt: "Crusader" },
    { src: "/images/nafc.jpg", alt: "NAFC" },
    { src: "/images/nbf.jpg", alt: "NBF" },
    { src: "/images/military.jpg", alt: "Military" },
    { src: "/images/stanbic.jpeg", alt: "Stanbic" },
    { src: "/images/bank.jpg", alt: "Bank" },
    { src: "/images/sterling.jpeg", alt: "Sterling" },
    { src: "/images/crusader.png", alt: "Crusader" },
    { src: "/images/nafc.jpg", alt: "NAFC" },
    { src: "/images/nbf.jpg", alt: "NBF" },
    { src: "/images/military.jpg", alt: "Military" },
    { src: "/images/stanbic.jpeg", alt: "Stanbic" },
    { src: "/images/bank.jpg", alt: "Bank" },
    { src: "/images/sterling.jpeg", alt: "Sterling" },
    { src: "/images/crusader.png", alt: "Crusader" },
    { src: "/images/nafc.jpg", alt: "NAFC" },
    { src: "/images/nbf.jpg", alt: "NBF" },
    { src: "/images/military.jpg", alt: "Military" },
    { src: "/images/stanbic.jpeg", alt: "Stanbic" },
    { src: "/images/bank.jpg", alt: "Bank" },
    { src: "/images/sterling.jpeg", alt: "Sterling" },
    { src: "/images/crusader.png", alt: "Crusader" },
    { src: "/images/nafc.jpg", alt: "NAFC" },
    { src: "/images/nbf.jpg", alt: "NBF" },
    { src: "/images/military.jpg", alt: "Military" },
    { src: "/images/stanbic.jpeg", alt: "Stanbic" },
    { src: "/images/bank.jpg", alt: "Bank" },
    { src: "/images/sterling.jpeg", alt: "Sterling" },
    { src: "/images/crusader.png", alt: "Crusader" },
    { src: "/images/nafc.jpg", alt: "NAFC" },
    { src: "/images/nbf.jpg", alt: "NBF" },
    { src: "/images/military.jpg", alt: "Military" },
    { src: "/images/stanbic.jpeg", alt: "Stanbic" },
    { src: "/images/bank.jpg", alt: "Bank" },
  ];
  
  export default sponsorImages;
  